arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: eyepetizer_localizations.dart
output-class: EyepetizerLocalizations
preferred-supported-locales:
  - en
use-deferred-loading: false
